project:
  type: book
  output-dir: _site

book:
  title: "NAULearningDataScience"
  author: "Ryan E Lima"
  date: "10/24/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - Notebooks\Kendalls_tau.ipynb
    - Notebooks\Morris_Elementary_Effects.ipynb
    - Notebooks\Sobol_variance.ipynb


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



